package org.vaadin.artur.solitaire;

import org.vaadin.artur.playingcards.CardPile;
import org.vaadin.artur.playingcards.CardStack;
import org.vaadin.artur.playingcards.Deck;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GameLayoutDesign extends GridLayout {
    protected Deck deck;
    protected CardPile deckPile;
    protected CardPile pile1;
    protected CardPile pile2;
    protected CardPile pile3;
    protected CardPile pile4;
    protected CardStack stack1;
    protected CardStack stack2;
    protected CardStack stack3;
    protected CardStack stack4;
    protected CardStack stack5;
    protected CardStack stack6;
    protected CardStack stack7;

    public GameLayoutDesign() {
        Design.read(this);
    }
}
